[versions]
android-plugins = "8.12.2"
android-room = "2.8.0-rc01"

sdk-compile = "36"
sdk-target = "36"
sdk-tools-build = "36.0.0"
sdk-min = "24"
sdk-ndk = "28.2.13676358"

app-code = "130"
app-name = "v1.30"

google-java-format = "1.28.0"
ktfmt = "0.56"
gradle-versions = "0.52.0"
spotless = "7.2.1"

[libraries]
plugin-android-application = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android-plugins" }
plugin-android-library = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android-plugins" }
plugin-jetbrains-kotlin-android = { module = "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin", version = "2.2.20" }

plugin-gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradle-versions" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

desugar_jdk_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version = "2.1.5" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }

libadb-android = { module = "com.github.MuntashirAkon:libadb-android", version = "3.1.0" }
sun-security-android = { module = "com.github.MuntashirAkon:sun-security-android", version = "1.1" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "6.1" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-browser = { module = "androidx.browser:browser", version = "1.9.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "android-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "android-room" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version = "1.1.0" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-beta01" }
androidx-webkit = { module = "androidx.webkit:webkit", version = "1.14.0" }

material = { module = "com.google.android.material:material", version = "1.13.0-rc01" }
guava = { module = "com.google.guava:guava", version = "33.4.8-android" }
better-link-movement-method = { module = "me.saket:better-link-movement-method", version = "2.2.0" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }

[plugins]
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]
