[versions]
android-plugins = "8.4.0"
android-room = "2.6.1"
compose-ui-tooling-runtime-livedata = "1.6.7"
compose-kotlin-compiler-ext = "1.5.13"

sdk-compile = "34"
sdk-target = "34"
sdk-tools-build = "34.0.0"
sdk-min = "24"
sdk-ndk = "25.1.8937393"

app-code = "125"
app-name = "v1.25"

[libraries]
plugin-android-application = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android-plugins" }
plugin-android-library = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android-plugins" }
plugin-jetbrains-kotlin-android = { module = "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin", version = "1.9.23" }

plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }
plugin-lsparanoid = { module = "org.lsposed.lsparanoid:gradle-plugin", version = "0.6.0" }

desugar_jdk = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.7.1" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
lsparanoid-core = { module = "org.lsposed.lsparanoid:core", version = "0.6.0" }

libadb-android = { module = "com.github.MuntashirAkon:libadb-android", version = "3.0.0" }
sun-security-android = { module = "com.github.MuntashirAkon:sun-security-android", version = "1.1" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "4.3" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "android-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "android-room" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version = "1.1.0-alpha06" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-alpha01" }
androidx-webkit = { module = "androidx.webkit:webkit", version = "1.11.0" }

material = { module = "com.google.android.material:material", version = "1.12.0" }
guava = { module = "com.google.guava:guava", version = "33.2.0-android" }
better-link-movement-method = { module = "me.saket:better-link-movement-method", version = "2.2.0" }
json = { module = "org.json:json", version = "20240303" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version = "1.9.0" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2024.05.00" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version = "1.2.1" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.7.7" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-ui-tooling-runtime-livedata" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui-tooling-runtime-livedata" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui-tooling-runtime-livedata" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version = "2.9.0" }

[plugins]
task-tree = { id = "com.dorongold.task-tree", version = "3.0.0" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
gradle-dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.31.0" }

[bundles]
